### ISSUE TITLE
Click throw element, swiping on element

### ISSUE THREAD

**Issue by W1nner7** [dnldsht/vue-insta-stories#10]
Hi, I'm using your stories with this component for my app - rate stars - https://primefaces.org/primevue/showcase/#/rating 

But, unfortunately, when clicking on any star element it's changing my current story slide...
How can I prevent any actions on my elements to don't swipe to the next or previous story?

**Comment by gilnd** [comment]
Hey @W1nner7 ,

Have you tried using event [modifiers](https://v3.vuejs.org/api/directives.html#v-on)? 
this should do the job ` v-on:click.prevent ` if you put it in your primevue component.

Lemme know if it fixed the issue, otherwise we would be happy to help if you could provide an implementation

Cheers! :)

**Comment by dnldsht** [comment]
If the modifiers didn't do the trick can you provide a codesandbox with your issue so we can investigate more, otherwise Im gonna close this issue
